### ISSUE TITLE
ideas about data section- a small mistake correction 

### ISSUE THREAD

**Issue by Rahafalmelabi** [3mmaRand/comp4biosci#1]
Dears,
I hope this email finds you well
I am writing to express my appreciation for your book, which I found to be both informative and simple. It is evident that a significant amount of effort has been put into its creation.
While reading through the ideas and data section, I came across a minor error that I believe would be beneficial for you to be aware of. I noticed that the variance symbol used was incorrect and instead the mean symbol was used.
I wanted to bring this to your attention in the spirit of constructive feedback. 

Thanks a lot

Best regards, 

Rahaf

**Comment by 3mmaRand** [comment]
Many thanks @Rahafalmelabi
